server:
  port: ${API_GATEWAY_PORT}

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_REALM_URI}
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: trip-service
          uri: lb://TRIP-SERVICE
          predicates:
            - name: Path
              args:
                patterns:
                  - "/trips/**"
                  - "/reservations/**"
                  - "/locations/**"
        - id: passenger-service
          uri: lb://PASSAGER-SERVICE
          predicates:
            - name: Path
              args:
                patterns:
                  - "/api/v1/passengers/**"
                  - "/api/v1/drivers-profile/**"

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://eureka-server:${EUREKA_SERVER_PORT}/eureka
