spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  instance:
    hostname: eureka-server
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

  server:
    enableSelfPreservation: true
