server:
  port: ${PAYMENT_SERVICE_PORT}

spring:
  application:
    name: payment-service

  main:
    web-application-type: reactive

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
