server:
  port: ${PAYMENT_SERVICE_PORT}

spring:
  application:
    name: payment-service

  main:
    web-application-type: reactive

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USER}
    password: ${RABBIT_MQ_PASS}
    virtual-host: /

  cloud:
    stream:
      default-binder: rabbit
      default:
        contentType: application/json
      bindings:
        reservationRequested-in-0:
          destination: reservation.exchange
          group: payment-service
        paymentAuthorized-out-0:
          destination: payment.exchange
        paymentFailed-out-0:
          destination: payment.exchange

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://eureka-server:${EUREKA_SERVER_PORT}/eureka
