server:
  port: ${TRIP_SERVICE_PORT}

spring:
  application:
    name: trip-service

  main:
    web-application-type: reactive

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USER}
    password: ${RABBIT_MQ_PASS}
    virtual-host: /

  cloud:
    function:
      definition: paymentAuthorized;paymentFailed
    stream:
      default-binder: rabbit
      default:
        contentType: application/json
      bindings:
        reservationRequested-out-0:
          destination: reservation.exchange
        reservationConfimedNotification-out-0:
          destination: notificaiton.exchange
        paymentAuthorized-in-0:
          destination: payment.exchange
          group: payment-service-authorized
          binder: rabbit
          consumer:
            bindingRoutingKey: payment.authorized
        paymentFailed-in-0:
          destination: payment.exchange
          group: payment-service-failed
          binder: rabbit
          consumer:
            bindingRoutingKey: payment.failed

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://eureka-server:${EUREKA_SERVER_PORT}/eureka
